version: '3.8'
name: easebnb_containers

services:
  # Database Section
  postgres_db:
    image: postgres:alpine3.18
    container_name: postgres_db_1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5435:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

networks:
  default:
    name: easebnb_network
    driver: bridge
