version: "3.8"
name: easebnb_containers

services:
  # Database Section
  postgres_db:
    image: postgis/postgis:16-3.4-alpine
    container_name: ease_pgdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
  easebnb_api:
    container_name: easebnb_api
    image: ${DOCKER_REGISTRY-}easebnb_api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: ../src
      dockerfile: ../src/Easebnb.WebApi/Dockerfile
    depends_on:
      - postgres_db
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "ASPNETCORE_URLS=http://+:80"
      - "DatabaseSetting:Host=postgres_db"
      - "DatabaseSetting:Port=5432"
      - "DatabaseSetting:Database=easebnb_db"
      - "DatabaseSetting:Username=admin"
      - "DatabaseSetting:Password=admin"
      - "DatabaseSetting:SslMode="
    ports:
      - "16111:80"
    restart: on-failure

networks:
  default:
    name: easebnb_network
    driver: bridge

volumes:
  postgres_data:
    driver: local
