name: easebnb_containers

services:
  postgres_db:
    image: postgis/postgis:16-3.4-alpine
    container_name: easebnb_pgdb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

  minio_storage:
    image: minio/minio:latest
    container_name: easebnb_minio
    environment:
        MINIO_ROOT_USER: admin
        MINIO_ROOT_PASSWORD: admin@2024AAA
    ports:
        - "9009:9000"
        - "9010:9001"
    volumes:
        - minio_data:/data
    command: server --console-address ":9001" /data
    
  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - portainer_data:/data
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 9000:9000
  #     - 8000:8000

networks:
  default:
    name: easebnb_network
    driver: bridge

volumes:
  postgres_data:
    driver: local
  portainer_data:
    driver: local
  minio_data:
    driver: local
